export const MetricsAction = {
    GET_TASK_METRICS_REQUEST: '@@metrics/GET_TASK_METRICS_REQUEST',
    GET_TASK_METRICS_REQUEST_SUCCESS: '@@metrics/GET_TASK_METRICS_REQUEST_SUCCESS',
    GET_TASK_METRICS_REQUEST_ERROR: '@@metrics/GET_TASK_METRICS_REQUEST_ERROR',
};