export const INDICATORS = {
    GET_INDICATORS_LIST_REQUEST: 'indicatorsList/GET_INDICATORS_LIST_REQUEST',
    GET_INDICATORS_LIST_SUCCESS: 'indicatorsList/GET_INDICATORS_LIST_SUCCESS',
    GET_INDICATORS_LIST_ERROR: 'indicatorsList/GET_INDICATORS_LIST_ERROR',
};