export const INDICATOR_CONFIG = {
    GET_INDICATOR_CONFIG_REQUEST: 'indicator/GET_INDICATOR_CONFIG_REQUEST',
    GET_INDICATOR_CONFIG_SUCCESS: 'indicator/GET_INDICATOR_CONFIG_SUCCESS',
    GET_INDICATOR_CONFIG_ERROR: 'indicator/GET_INDICATOR_CONFIG_ERROR',
};