
// TODO DEPRECATED
export const GENERAL_CONFIG_CONSTANTS = {
    SET_LONG_PERIOD_FROM: "generalConfig/SET_LONG_PERIOD_FROM",
    SET_LONG_PERIOD_TO: "generalConfig/SET_LONG_PERIOD_TO",
    SET_SHORT_PERIOD_FROM: "generalConfig/SET_SHORT_PERIOD_FROM",
    SET_SHORT_PERIOD_TO: "generalConfig/SET_SHORT_PERIOD_TO",
    SET_LONG_PERIOD_STEP: "generalConfig/SET_LONG_PERIOD_STEP",
    SET_SHORT_PERIOD_STEP: "generalConfig/SET_SHORT_PERIOD_STEP",
    SET_INTERVAL: "generalConfig/SET_INTERVAL",
}