export const StatsAction = {
    GET_TASK_STATS_REQUEST: '@@stats/GET_TASK_STATS_REQUEST',
    GET_TASK_STATS_REQUEST_SUCCESS: '@@stats/GET_TASK_STATS_REQUEST_SUCCESS',
    GET_TASK_STATS_REQUEST_ERROR: '@@stats/GET_TASK_STATS_REQUEST_ERROR',
};