export const INDICATORS = {
    GET_INDICATORS_LIST_REQUEST: 'indicators/GET_INDICATORS_LIST_REQUEST',
    GET_INDICATORS_LIST_SUCCESS: 'indicators/GET_INDICATORS_LIST_SUCCESS',
    GET_INDICATORS_LIST_ERROR: 'indicators/GET_INDICATORS_LIST_ERROR',
    // GET_INDICATOR_CONFIG_REQUEST: 'indicators/GET_INDICATOR_CONFIG_REQUEST',
    // GET_INDICATOR_CONFIG_SUCCESS: 'indicators/GET_INDICATOR_CONFIG_SUCCESS',
    // GET_INDICATOR_CONFIG_ERROR: 'indicators/GET_INDICATOR_CONFIG_ERROR',
};