export const TRADING_PAIR = {
    GET_TRADING_PAIR_LIST_REQUEST: 'tradingPair/GET_TRADING_PAIR_LIST_REQUEST',
    GET_TRADING_PAIR_LIST_SUCCESS: 'tradingPair/GET_TRADING_PAIR_LIST_SUCCESS',
    GET_TRADING_PAIR_LIST_ERROR: 'tradingPair/GET_TRADING_PAIR_LIST_ERROR',
};