export const AppPropertiesAction = {
    GET_APP_PROPERTIES_REQUEST: '@@appProperties/GET_APP_PROPERTIES_REQUEST',
    GET_APP_PROPERTIES_SUCCESS: '@@appProperties/GET_APP_PROPERTIES_SUCCESS',
    GET_APP_PROPERTIES_ERROR: '@@appProperties/GET_APP_PROPERTIES_ERROR',
};