export const TaskAction = {
    GET_TASK_PROGRESS_REQUEST: '@@task/GET_TASK_PROGRESS_REQUEST',
    GET_TASK_PROGRESS_REQUEST_SUCCESS: '@@task/GET_TASK_PROGRESS_SUCCESS',
    GET_TASK_PROGRESS_REQUEST_ERROR: '@@task/GET_TASK_PROGRESS_ERROR',

    RUN_TASK_OPTIMIZATION_REQUEST: '@@task/RUN_TASK_OPTIMIZATION_REQUEST',
    RUN_TASK_OPTIMIZATION_REQUEST_SUCCESS: '@@task/RUN_TASK_OPTIMIZATION_REQUEST_SUCCESS',
    RUN_TASK_OPTIMIZATION_REQUEST_ERROR: '@@task/RUN_TASK_OPTIMIZATION_REQUEST_ERROR',
};