export const PlotAction = {
    GET_ASSET_PLOT_REQUEST: '@@plot/GET_ASSET_PLOT_REQUEST',
    GET_ASSET_PLOT_SUCCESS: '@@plot/GET_ASSET_PLOT_SUCCESS',
    GET_ASSET_PLOT_ERROR: '@@plot/GET_ASSET_PLOT_ERROR',

    GET_TASK_PLOT_REQUEST: '@@plot/GET_TASK_PLOT_REQUEST',
    GET_TASK_PLOT_SUCCESS: '@@plot/GET_TASK_PLOT_SUCCESS',
    GET_TASK_PLOT_ERROR: '@@plot/GET_TASK_PLOT_ERROR',
};