export const SIGN_UP_ACTION_TYPES = {
    DO_SIGNUP_REQUEST: '@@signup/DO_SIGNUP_REQUEST',
    DO_SIGNUP_REQUEST_SUCCESS: '@@signup/DO_SIGNUP_REQUEST_SUCCESS',
    DO_SIGNUP_REQUEST_ERROR: '@@signup/DO_SIGNUP_REQUEST_ERROR',
};