export const ParametersAction = {
    GET_TASK_PARAMETERS_REQUEST: '@@parameters/GET_TASK_PARAMETERS_REQUEST',
    GET_TASK_PARAMETERS_REQUEST_SUCCESS: '@@parameters/GET_TASK_PARAMETERS_REQUEST_SUCCESS',
    GET_TASK_PARAMETERS_REQUEST_ERROR: '@@parameters/GET_TASK_PARAMETERS_REQUEST_ERROR',
};